name: checking
on:
  push:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.10", "3.12" ]
    steps:
    - name: Checkouts Repository
      uses: actions/checkout@v3

    - name: Set up python ${{matrix.python-version}}
      uses: action/setup-python@v4
      with:
        python-version: ${{matrix.python-version}}
    
    - name: checking
      run: |
        python -m install pip --upgrade pip
        python -m install tox
        tox